spring:
  application.name: board
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: dev
    group:
      "prod": "local, prod"
      "dev": "local, dev, sensitive"

mybatis:
  type-aliases-package: com.knou.board.domain
  type-handlers-package: com.knou.board.domain
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
