server:
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  application.name: board
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  profiles:
    active: local-dev
    group:
      "prod": "local, prod"  # 배포서버
      "local-dev": "local, sensitive"  # 로컬 개발환경

mybatis:
  type-aliases-package: com.knou.board.domain
  type-handlers-package: com.knou.board.domain
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.knou.board.repository.mybatis: DEBUG