config:
  activate.on-profile: prod
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://158.247.245.81:3306/bangcom_product?createDatabaseIfNotExist=true
    username: root
    password: root9999
custom:
  path:
    image: 'file:///root/board-resources/images/'
    upload-image: '/root/board-resources/images/'

logging:
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul
  file.name: /var/log/board.log
  level:
    com.knou.board: ERROR
    org.springframework.jdbc: ERROR
    com.knou.board.repository.mybatis: ERROR