server:
  port: 8084


spring:
  application.name: board
  profiles.active: sensitive
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
mybatis:
  type-aliases-package: com.knou.board.domain
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.knou.board.repository.mybatis: DEBUG
